arcade/arcade.go, board/board.go, board/board_utils.go, main.go, player/player.go
=> Feature: board basic functionalities

arcade/arcade.go, board/board.go, go.mod, go.sum, main.go, player/player.go, server/handlers.go, server/server.go
GET /
GET /match/new
GET /match/{id}
POST /match/{id}/move (json body: {"playerId": 1, "posX": 3, "posY": 0} )
closes #2
=> Mux server: basic routes and handlers

server/handlers.go, server/server.go
=> Add cors middleware

board/board_test.go
Add a first unit test for function board.CheckCaptures.
Closes #15 and a checkbox in #4 :)
=> Create first unit test (for checking captures)

arcade/arcade.go, front/src/components/Arcade.vue, front/src/components/Match.vue, front/src/store/store.js, main.go, player/player.go, server/handlers.go, server/server.go
Current AI status of player is not present, but it's needed as a condition for gameplay.
- Back: Add AI status to players and as required new match args
- Add AI status to front
Closes #19
=> Feature: Add player AI status to game state

board/board.go, board/board_test.go, board/board_utils.go
=> Add tests for placing and protect functions

front/src/components/Board.vue, front/src/components/Tile.vue, front/src/store/store.js, front/tailwind.config.js
Highlights suggested position in board in web interface. Not pretty. :)
Closes #29
=> Add suggested position to store plus ugly-useful CSS

board/board_test.go
=> Fix: repair tests, player struct updated

arcade/arcade.go, board/board.go, server/handlers.go
Adds captures to match history.
Closes #31
=> Add captures to history

arcade/arcade.go, board/board.go, board/board_test.go, heuristic/heuristic.go
=> Fix: captures counters are not modified by suggestor

arcade/arcade.go, server/handlers.go, server/server.go
Removes last move from history, removes the stone from board and replaces captured stones in last move
Closes #32
=> Feature: unapply move

front/package.json, front/public/index.html, front/src/App.vue, front/src/assets/styles.css, front/src/assets/tailwind.css, front/src/components/Arcade.vue, front/src/components/Board.vue, front/src/components/Match.vue, front/src/components/Tile.vue, front/src/main.js, front/src/store/store.js, front/tailwind.config.js, front/yarn.lock
Add some colors and fonts from v1
Add (messy) logic for stone styles
Show suggestion
Tile colors ok
Closes #3
=> Feature(front): Style GUI

arcade/arcade.go, board/board.go
=> Feature: verify it's player's turn before placing stone

board/board.go
=> Feature: Player wins if he captures 10 or more stones

front/src/App.vue, front/src/assets/styles.css, front/src/components/Board.vue, front/src/components/Match.vue, front/src/store/store.js, front/tailwind.config.js
- Add undo button
- Update button styles
Closes #41
=> Feature(front): Add undo button

arcade/arcade.go, arcade/arcade_test.go, board/board_test.go
=> Test: Add arcade tests and turn verification

server/handlers.go
=> Truncate history in HTTP response to 2 moves max

front/package.json, front/src/App.vue, front/src/assets/styles.css, front/src/components/Board.vue, front/src/components/Match.vue, front/src/components/Tile.vue, front/src/main.js, front/src/router.js, front/src/store/store.js, front/yarn.lock
- Add route with match ID to established matches
- Improve error messages
Closes #42
=> Feature(front): Add client-side routing

arcade/arcade.go, board/board.go, heuristic/heuristic.go
- Add Node struct
- Keep dumb suggestion and setup tree building
- Add function to remove stone from board to board pkg and LastMove->CurrentMove
- Apply moves to temporary board in tree
Closes #65
=> Feature(core): Set up possible move tree

ai/ai.go, ai/ai_test.go, arcade/arcade.go, arcade/arcade_test.go, arcade/match/match.go, server/handlers.go
Create a match subpackage inside arcade package
Closes #67
=> Refactor: separate match from arcade

front/package.json, front/src/App.vue, front/src/store/store.js, front/yarn.lock
- Install and use axios in getMatch
- Set current player to P1 when no move history
- Move and add padding to attr link :)
Create new empty game; refresh the page or navigate to another match, then return to new game. Player should still be player 1 by default, and no errors should appear when resuming normal gameplay.
Fixes #73
=> Fix(front): Fix problem with current player ID on new games

front/src/App.vue, front/src/assets/spinner.css, front/src/components/Board.vue, front/src/components/Tile.vue, front/src/pages/Match.vue, front/src/store/store.js
=> Fix(front): Block interaction on http pending
